In [8]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\ANKIT PATEL\anaconda3\envs\Python_Sales_Analytics\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\ANKIT PATEL\anaconda3\envs\Python_Sales_Analytics\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\ANKIT PATEL\anaconda3\envs\Python_Sales_Analytics\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 645.7 kB/s eta 0:00:15
   -- ------------------------------------- 0.5/9.7 MB 645.7 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/9.7 MB 699.0 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.7 MB 740.5 kB/s eta 0:00:12
   ---- ----------------------------------- 1.0/9.7 MB 740.5 kB/s eta 0:00:12
   ----- ---------------------------------- 1.3/9.7 MB 762.6 kB/s eta 0:00:11
   ------ --------------------------------- 1.6/9.7 MB 806.6 kB/s eta 0:00:11
   ------ --------------------------------- 1.6/9.7 MB 806.6 kB/s eta 0:00:11
   ------- -------------------------------- 1.8/9.7 MB 812.0 kB/s eta 0:00:10
   -------- ------------------------------- 2.1/9.7 MB 810.2 kB/s eta 0:00:10
   --------- ------------------------------ 2.4/9.7 MB 838.9 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/9.7 MB 862.9 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.7 MB 892.6 kB/s eta 0:00:08
   ------------- -------------------------- 3.1/9.7 MB 913.7 kB/s eta 0:00:08
   -------------- ------------------------- 3.4/9.7 MB 936.5 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.7 MB 944.3 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.7 MB 944.3 kB/s eta 0:00:07
   ---------------- ----------------------- 3.9/9.7 MB 951.0 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.7 MB 949.8 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.7 MB 955.4 kB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.7 MB 960.4 kB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.7 MB 960.4 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.7 MB 964.9 kB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.7 MB 969.0 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.7 MB 981.1 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 981.5 kB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.7 MB 992.3 kB/s eta 0:00:04
   -------------------------- ------------- 6.3/9.7 MB 994.6 kB/s eta 0:00:04
   --------------------------- ------------ 6.6/9.7 MB 996.7 kB/s eta 0:00:04
   --------------------------- ------------ 6.6/9.7 MB 996.7 kB/s eta 0:00:04
   ---------------------------- ----------- 6.8/9.7 MB 996.3 kB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.7 MB 995.9 kB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.7 MB 1,000.0 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.7 MB 1.0 MB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.7 MB 1.0 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.7 MB 1.0 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.7 MB 1.0 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.7 MB 1.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 1.1 MB/s  0:00:09
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.6 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

In [20]:
Customers = pd.read_csv("../data/Customers.csv")
Orders = pd.read_csv("../data/Orders.csv")
Order_Details = pd.read_csv("../data/Order_Details.csv")
Products = pd.read_csv("../data/Products.csv")
Targets = pd.read_csv("../data/Targets.csv")

Check first 5 rows

In [15]:
print("Customers")
display(Customers.head())

Customers

,Customer_ID,Customer_Name,Gender,Age,City,State,Region
0,CUST000001,Aarav Sethi,Male,25,Raipur,Chhattisgarh,Central
1,CUST000002,Varun Sinha,Male,33,Pune,Maharashtra,West
2,CUST000003,Aditi Sethi,Female,29,Kolkata,West Bengal,East
3,CUST000004,Swati Thakur,Female,37,Bhubaneswar,Odisha,East
4,CUST000005,Varun Malhotra,Male,28,Indore,Madhya Pradesh,Central

In [22]:
print("Products")
display(Products.head())

Products

,Product_ID,Product_Name,Category,Sub_Category,Brand,Cost_Price,Selling_Price
0,PRD000001,HUL Apples 250ml,Fruits & Vegetables,Fresh Fruits,HUL,35,40
1,PRD000002,Lux Apples 500g,Fruits & Vegetables,Fresh Fruits,Lux,40,55
2,PRD000003,Lux Apples Pack of 6,Fruits & Vegetables,Fresh Fruits,Lux,85,110
3,PRD000004,Harpic Apples Pack of 4,Fruits & Vegetables,Fresh Fruits,Harpic,90,110
4,PRD000005,PepsiCo Apples 1kg,Fruits & Vegetables,Fresh Fruits,PepsiCo,80,94

In [23]:
print("Orders")
display(Orders.head())

Orders

,Order_ID,Order_Date,Customer_ID,Payment_Method,Order_Status,Year,Month_Name,Quarter,Day,Weekday,Month,Region
0,ORD000001,15-12-2023,CUST003379,Credit Card,Delivered,2023,12,Q4,15,Friday,Dec-23,South
1,ORD000002,06-06-2023,CUST008843,UPI,Delivered,2023,6,Q2,6,Tuesday,Jun-23,West
2,ORD000003,14-06-2023,CUST008484,UPI,Delivered,2023,6,Q2,14,Wednesday,Jun-23,Central
3,ORD000004,22-09-2023,CUST000833,UPI,Delivered,2023,9,Q3,22,Friday,Sep-23,South
4,ORD000005,17-11-2025,CUST009978,UPI,Delivered,2025,11,Q4,17,Monday,Nov-25,North

In [21]:
print("Order_Details")
display(Order_Details.head())

Order_Details

,Order_ID,Product_ID,Quantity,Discount,Selling_Price,Cost_Price,Gross_Sales,Discount_Amount,Net_Sales,Total_Cost,Profit,Profit_Margin,Customer_ID,Order_Date,Month,Month_start,Region,Category
0,ORD000001,PRD000116,3,0.00,175,135,525,0.0,525.0,405,120.0,0.228571,CUST003379,2023-12-15,Dec-23,2023-12-01,South,Fruits & Vegetables
1,ORD000001,PRD000344,1,0.00,50,45,50,0.0,50.0,45,5.0,0.100000,CUST003379,2023-12-15,Dec-23,2023-12-01,South,Beverages
2,ORD000001,PRD000756,1,0.05,126,105,126,6.3,119.7,105,14.7,0.122807,CUST003379,2023-12-15,Dec-23,2023-12-01,South,Staples
3,ORD000002,PRD000878,1,0.15,40,25,40,6.0,34.0,25,9.0,0.264706,CUST008843,2023-06-06,Jun-23,2023-06-01,West,Bakery
4,ORD000002,PRD000415,1,0.10,54,35,54,5.4,48.6,35,13.6,0.279835,CUST008843,2023-06-06,Jun-23,2023-06-01,West,Snacks

In [26]:
print("Targets")
display(Targets.head())

Targets

     Month   Region  Sales_Target  Profit_Target
0  2022-01    North       3660000         546000
1  2022-01    South       4060000         626000
2  2022-01     East       2520000         347000
3  2022-01     West       4750000         752000
4  2022-01  Central       2710000         372000

Check dataset shape

In [28]:
print("Customers Shape:", Customers.shape)
print("Products Shape:", Products.shape)
print("Orders Shape:", Orders.shape)
print("Order Details Shape:",Order_Details.shape)
print("Targets Shape:", Targets.shape)

Customers Shape: (10000, 7)
Products Shape: (1392, 7)
Orders Shape: (400000, 12)
Order Details Shape: (1019516, 18)
Targets Shape: (240, 4)